### ISSUE TITLE
Update README - require 'geckoboard'

### ISSUE THREAD

**Issue by diasks2** [geckoboard/geckoboard-ruby#12]
I'd recommend adding `require 'geckoboard'` to the README. I found it in the developer docs (https://developer.geckoboard.com/api-reference/ruby/), but before that I was spinning my wheels on why I was getting a `NameError: uninitialized constant Geckoboard`.

**Comment by jnormington** [comment]
Hey @diasks2, 

Thanks for taking to the time to raise the issue and for the delay in making this change. This is now in the readme.
