### ISSUE TITLE
Undefined Method Numberfield.

### ISSUE THREAD

**Issue by yragnos** [geckoboard/geckoboard-ruby#13]
2.3.1 :001 > require 'geckoboard'
 => true 
2.3.1 :002 > client = Geckoboard.client(ENV["GECKOBOARD_API_KEY"])
 => #<Geckoboard::Client:0x00000005b45fc8 @connection=#<Geckoboard::Connection:0x00000005b45fa0 @api_key="apisecretkey-corect">> 
2.3.1 :003 > client.ping
 => true 
2.3.1 :004 > dataset = client.datasets.find_or_create('sales.gross', fields: [
2.3.1 :005 >         Geckoboard::MoneyField.new(:cost, name: 'Cost', currency_code: 'USD'),
2.3.1 :006 >         Geckoboard::DateTimeField.new(:timestamp, name: 'Time'),
2.3.1 :007 >         Geckoboard::NumberField(:amount, name: 'Amount', optional: true)
2.3.1 :008?>     ], unique_by: [:timestamp])
NoMethodError: undefined method `NumberField' for Geckoboard:Module

**Comment by jnormington** [comment]
Hey @yragnos,

Thanks for trying the ruby datasets library and raising the issue. It appears that you are missing the .new initializer on the NumberField class as its not a method.

But it appears that our readme had the incorrect example which your example is based off. We have now fixed this in the readme, below is the corrected example.

```ruby
require 'geckoboard'
client = Geckoboard.client(ENV["GECKOBOARD_API_KEY"])
client.ping

dataset = client.datasets.find_or_create('sales.gross', fields: [
  Geckoboard::MoneyField.new(:cost, name: 'Cost', currency_code: 'USD'),
  Geckoboard::DateTimeField.new(:timestamp, name: 'Time'),
  Geckoboard::NumberField.new(:amount, name: 'Amount', optional: true)
], unique_by: [:timestamp])
```

If you still experience any further problems let us know!

**Comment by yragnos** [comment]
Thanks that fixed it - I will work through the examples and post any issues I find.
