### ISSUE TITLE
uninitialized constant Geckoboard::MoneyField

### ISSUE THREAD

**Issue by rovitulli** [geckoboard/geckoboard-ruby#6]
Hi, there.

Do you have any ideas why am I getting a _uninitialized constant Geckoboard::MoneyField_ ?

        def create_dataset
           dataset = @client.datasets.find_or_create('active.products', fields: [
                                                Geckoboard::MoneyField.new(:amount, name: 'Amount', currency: 'USD')])
        end

the @client var I declared in a client method above and works fine. 
I browsed your code and executed the specs and all seems to work.

**Comment by rovitulli** [comment]
I think I got it. Rubygems points to version 0.1.0, which has no _field_types_ yet. I pointed to the _master_ in my Gemfile and it worked. I'm sorry I didn't notice that before.

**Comment by coreycondardo** [comment]
I'm getting the same problem. I added:
```
gem 'geckoboard-ruby', :git => 'https://github.com/geckoboard/geckoboard-ruby.git'
```
to my Gemfile, but still I get the uninitialized constant error.

**Comment by boxofrad** [comment]
Thanks for raising this @rovitulli & for your input @coreycondardo 😄 

Well this is a little embarrassing... It looks like I published the docs before cutting a new release of the gem 😳  

I've now release v0.2.0 so if you `bundle update geckoboard-ruby` you should be good to go.

Sorry about that!
